services:
  VidyaMitraDbServer:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      SA_PASSWORD: "HumTum@@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  authapi:
    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/vidyamitra.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "VidyaMitra123"
      ConnectionStrings__AuthConnection: "Server=VidyaMitraDbServer;Database=VMAuthDB;User ID=sa;Password=HumTum@@;TrustServerCertificate=True;"
      ApiSettings__JwtOptions__Secret: "YourSuperSecretSecureUnbreakableKeyOf256BitsLength!"
      ApiSettings__JwtOptions__Issuer: "VidyaMitra"
      ApiSettings__JwtOptions__Audience: "VidyaMitraUsers"
      ApiSettings__JwtOptions__ExpiryInMinutes: "60"
    depends_on:
      - VidyaMitraDbServer
    ports:
      - "7040:443"
    volumes:
      - ./certs/vidyamitra.pfx:/https/vidyamitra.pfx:ro

  vidyamitraapi:
    build:
      context: .
      dockerfile: VidyaMitra.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "https://+:443"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/vidyamitra.pfx"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "VidyaMitra123"
      ConnectionStrings__VidyaMitraConnection: "Server=VidyaMitraDbServer;Database=VidyaMitraDB;User ID=sa;Password=HumTum@@;TrustServerCertificate=True;Persist Security Info=True;"
      ServiceUrls__AuthApiBase: "https://authapi:443"
    depends_on:
      - VidyaMitraDbServer
      - authapi
    ports:
      - "7050:443"
    volumes:
      - ./certs/vidyamitra.pfx:/https/vidyamitra.pfx:ro

  vidyamitra-client:
    build:
      context: ./VidyaMitra.Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - vidyamitraapi

volumes:
  mssqldata:
    driver: local
